openapi: 3.0.2
info:
  version: 1.0.0
  title: 'SAP Commerce Cloud - Management API'
  description: 'The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.'
  license:
    name: 'Use of this file is subject to the terms of your agreement with SAP SE or its affiliates respecting the use of the SAP product for which this file relates.'

x-sap-api-type: REST
x-sap-shortText: Manage Commerce Cloud Automation.
x-sap-stateInfo:
  state: Beta
servers:
  - url: https://{uri}/{version}
    description: Environment URL
    variables:
      uri:
        default: 'portalrotapi.hana.ondemand.com'
        description: Environment URI
      version:
        default: 'v1'
        description: API version
tags:
  - name: permissions
    description: Endpoints for managing permissions
  - name: environment
    description: Endpoints for managing environments
paths:
  /permissions:
    get:
      tags:
        - permissions
      description: Get subscription permissions
      operationId: getPermissions
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionsDetailDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment details
      operationId: getEnvironment
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentDetailDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/health:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment health
      operationId: getEnvironmentHealth
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentHealthDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/services:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment services
      operationId: getEnvironmentServices
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicesDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/services/{serviceCode}/replicas/{replicaName}:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
      - name: serviceCode
        in: path
        description: Service code
        required: true
        schema:
          type: string
      - name: replicaName
        in: path
        description: Replica name
        required: true
        schema:
          type: string
    delete:
      tags:
        - service
      description: Restart replica of the service
      operationId: restartReplica
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceReplicaStatusDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/mediaStorage/{mediaStorageCode}/showkey:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
      - name: mediaStorageCode
        in: path
        description: Media storage in the environment
        required: true
        schema:
          type: string
    post:
      tags:
        - environment
      description: Get public key for media storage
      operationId: getMediaStoragePublicKey
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaStoragePublicKeyDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
security:
  - OAuth2: [ ]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            { }
          authorizationUrl: 'https://oauthasservices-a9f746d57.hana.ondemand.com/oauth2/api/v1/authorize'
          tokenUrl: 'https://oauthasservices-a9f746d57.hana.ondemand.com/oauth2/api/v1/token'
  parameters:
    EndpointWebProxyFilter:
      name: webProxy
      in: query
      description: The web proxy by which to filter endpoints, possible values are "public", "private" or "nat"
      required: false
      schema:
        type: string
    EndpointServiceFilter:
      name: service
      in: query
      description: The service by which to filter endpoints
      required: false
      schema:
        type: string
  responses:
    DefaultResponse:
      description: Generic error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
  schemas:
    ErrorDTO:
      description: Problem detail message (https://tools.ietf.org/html/rfc7807)
      type: object
      properties:
        title:
          description: Human-readable summary of the problem type
          type: string
          readOnly: true
        detail:
          description: Human-readable explanation specific to this occurrence of the problem
          type: string
          readOnly: true
    EnvironmentDetailDTO:
      description: Entity to represent an environment
      type: object
      properties:
        subscriptionCode:
          description: Subscription code
          type: string
        name:
          description: Environment name
          type: string
        code:
          description: Environment code
          type: string
        live:
          description: Live
          type: boolean
        loggingUrl:
          description: Logging URL
          type: string
        dynatraceUrl:
          description: Dynatrace URL
          type: string
        mediaStorages:
          description: Media Storages
          type: array
          items:
            $ref: '#/components/schemas/MediaStorageDTO'
    EnvironmentHealthDTO:
      description: Entity to represent problems of the environment
      type: object
      properties:
        problems:
          description: Dynatrace problems
          type: integer
    MediaStorageDTO:
      description: Entity to represent a media storage
      type: object
      required:
        - code
        - name
        - accountName
        - publicUrl
      properties:
        code:
          description: Description
          type: string
        name:
          description: Name
          type: string
        accountName:
          description: Account Name
          type: string
        publicUrl:
          description: Public URL
          type: string
    PermissionsDetailDTO:
      description: Entity to represent permissions to all subscriptions of the current user
      type: object
      properties:
        username:
          description: User name
          type: string
        permissionDTOS:
          description: Permissions for each subscription
          type: array
          items:
            $ref: '#/components/schemas/PermissionDTO'
    PermissionDTO:
      description: Entity to represent permissions to a specific subscription
      type: object
      required:
        - scopeName
        - permissions
      properties:
        scopeName:
          description: Subscription id
          type: string
        permissions:
          type: array
          items:
            type: string
        environments:
          description: List of environment codes current user has access
          type: array
          items:
            type: string
    MediaStoragePublicKeyDTO:
      description: Entity to represent media storage public key
      type: object
      required:
        - publicKey
      properties:
        publicKey:
          description: Public Key
          type: string
    ServicesDTO:
      description: Collection of environment services
      type: array
      items:
        $ref: '#/components/schemas/ServiceDTO'
    ServiceDTO:
      description: Entity to represent environment service
      type: object
      required:
        - code
        - name
        - modifiedBy
        - modifiedTime
        - customerScalableSupported
        - runnable
      properties:
        code:
          type: string
        name:
          type: string
        modifiedBy:
          type: string
        modifiedTime:
          type: string
          format: date-time
        customerScalableSupported:
          type: boolean
        runnable:
          type: boolean
        desiredReplicas:
          type: integer
        availableReplicas:
          type: integer
        replicas:
          type: array
          items:
            $ref: '#/components/schemas/ServiceReplicaDTO'
    ServiceReplicaDTO:
      type: object
      required:
        - name
        - status
        - type
      properties:
        name:
          type: string
        status:
          type: string
        ready:
          type: boolean
    ServiceReplicaStatusDTO:
      type: object
      required:
        - code
        - type
        - createdBy
        - subscriptionCode
        - environmentCode
        - replica
        - serviceCode
      properties:
        code:
          type: string
        type:
          type: string
        status:
          type: string
        endTime:
          type: string
          format: date-time
        startTime:
          type: string
          format: date-time
        createdBy:
          type: string
        subscriptionCode:
          type: string
        environmentCode:
          type: string
        replica:
          type: string
        serviceCode:
          type: string
