openapi: 3.0.2
info:
  version: 1.0.1
  title: 'SAP Commerce Cloud - Management API'
  description: 'The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.'
  license:
    name: 'Use of this file is subject to the terms of your agreement with SAP SE or its affiliates respecting the use of the SAP product for which this file relates.'

x-sap-api-type: REST
x-sap-shortText: Manage Commerce Cloud Automation.
x-sap-stateInfo:
  state: Beta
servers:
  - url: https://{uri}/{version}
    description: Environment URL
    variables:
      uri:
        default: 'portalrotapi.hana.ondemand.com'
        description: Environment URI
      version:
        default: 'v1'
        description: API version
tags:
  - name: permissions
    description: Endpoints for managing permissions
  - name: environment
    description: Endpoints for managing environments
  - name: endpoint
    description: Endpoints for managing endpoints
paths:
  /permissions:
    get:
      tags:
        - permissions
      description: Get subscription permissions
      operationId: getPermissions
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionsDetailDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment details
      operationId: getEnvironment
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/health:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment health
      operationId: getEnvironmentHealth
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentHealthDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/services:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    get:
      tags:
        - environment
      description: Get environment services
      operationId: getEnvironmentServices
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicesDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/services/{serviceCode}/replicas/{replicaName}:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
      - name: serviceCode
        in: path
        description: Service code
        required: true
        schema:
          type: string
      - name: replicaName
        in: path
        description: Replica name
        required: true
        schema:
          type: string
    delete:
      tags:
        - service
      description: Restart replica of the service
      operationId: restartReplica
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceReplicaStatusDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/mediaStorage/{mediaStorageCode}/showkey:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
      - name: mediaStorageCode
        in: path
        description: Media storage in the environment
        required: true
        schema:
          type: string
    post:
      tags:
        - environment
      description: Get public key for media storage
      operationId: getMediaStoragePublicKey
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaStoragePublicKeyDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
  /subscriptions/{subscriptionCode}/environments/{environmentCode}/endpoints:
    parameters:
      - name: subscriptionCode
        in: path
        description: Customer subscription code
        required: true
        schema:
          type: string
      - name: environmentCode
        in: path
        description: Environment in the subscription
        required: true
        schema:
          type: string
    patch:
      tags:
        - endpoint
      description: Update endpoints maintenance mode
      operationId: updateEndpointsMaintenanceMode
      parameters:
        - $ref: '#/components/parameters/EndpointWebProxyFilter'
        - $ref: '#/components/parameters/EndpointServiceFilter'
      requestBody:
        description: Endpoints maintenance mode info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointsUpdateDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentDTO'
        '4XX':
          $ref: '#/components/responses/DefaultResponse'
        '5XX':
          $ref: '#/components/responses/DefaultResponse'
security:
  - OAuth2: [ ]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            { }
          authorizationUrl: 'https://oauthasservices-a9f746d57.hana.ondemand.com/oauth2/api/v1/authorize'
          tokenUrl: 'https://oauthasservices-a9f746d57.hana.ondemand.com/oauth2/api/v1/token'
  parameters:
    EndpointWebProxyFilter:
      name: webProxy
      in: query
      description: The web proxy by which to filter endpoints, possible values are "public", "private" or "nat"
      required: false
      schema:
        type: string
    EndpointServiceFilter:
      name: service
      in: query
      description: The service by which to filter endpoints
      required: false
      schema:
        type: string
  responses:
    DefaultResponse:
      description: Generic error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
  schemas:
    ErrorDTO:
      description: Problem detail message (https://tools.ietf.org/html/rfc7807)
      type: object
      properties:
        title:
          description: Human-readable summary of the problem type
          type: string
          readOnly: true
        detail:
          description: Human-readable explanation specific to this occurrence of the problem
          type: string
          readOnly: true
    EnvironmentHealthDTO:
      description: Entity to represent problems of the environment
      type: object
      properties:
        problems:
          description: Dynatrace problems
          type: integer
    PermissionsDetailDTO:
      description: Entity to represent permissions to all subscriptions of the current user
      type: object
      properties:
        username:
          description: User name
          type: string
        permissionDTOS:
          description: Permissions for each subscription
          type: array
          items:
            $ref: '#/components/schemas/PermissionDTO'
    PermissionDTO:
      description: Entity to represent permissions to a specific subscription
      type: object
      required:
        - scopeName
        - permissions
      properties:
        scopeName:
          description: Subscription id
          type: string
        permissions:
          type: array
          items:
            type: string
        environments:
          description: List of environment codes current user has access
          type: array
          items:
            type: string
    MediaStoragePublicKeyDTO:
      description: Entity to represent media storage public key
      type: object
      required:
        - publicKey
      properties:
        publicKey:
          description: Public Key
          type: string
    ServicesDTO:
      description: Collection of environment services
      type: array
      items:
        $ref: '#/components/schemas/ServiceDTO'
    ServiceDTO:
      description: Entity to represent environment service
      type: object
      required:
        - code
        - name
        - modifiedBy
        - modifiedTime
        - customerScalableSupported
        - runnable
      properties:
        code:
          type: string
        name:
          type: string
        modifiedBy:
          type: string
        modifiedTime:
          type: string
          format: date-time
        customerScalableSupported:
          type: boolean
        runnable:
          type: boolean
        desiredReplicas:
          type: integer
        availableReplicas:
          type: integer
        replicas:
          type: array
          items:
            $ref: '#/components/schemas/ServiceReplicaDTO'
    ServiceReplicaDTO:
      type: object
      required:
        - name
        - status
        - type
      properties:
        name:
          type: string
        status:
          type: string
        ready:
          type: boolean
    ServiceReplicaStatusDTO:
      type: object
      required:
        - code
        - type
        - createdBy
        - subscriptionCode
        - environmentCode
        - replica
        - serviceCode
      properties:
        code:
          type: string
        type:
          type: string
        status:
          type: string
        endTime:
          type: string
          format: date-time
        startTime:
          type: string
          format: date-time
        createdBy:
          type: string
        subscriptionCode:
          type: string
        environmentCode:
          type: string
        replica:
          type: string
        serviceCode:
          type: string
    EndpointsUpdateDTO:
      description: Entity to represent environments endpoints update request
      type: object
      required:
        - endpoints
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/EndpointUpdateDTO'
    EndpointUpdateDTO:
      type: object
      properties:
        endpointCode:
          type: string
        webProxyCode:
          type: string
        maintenanceMode:
          type: boolean

    EnvironmentDTO:
      type: object
      properties:
        locale:
          type: string
        timezone:
          type: string
        code:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [ AVAILABLE, ... ]   # expand if needed
        operation:
          type: string
          nullable: true
        type:
          type: string
        webProxies:
          type: array
          items:
            $ref: '#/components/schemas/WebProxyDTO'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/EndpointDTO'
        envIpFilterSets:
          type: array
          items:
            type: string
        mediaStorages:
          type: array
          items:
            $ref: '#/components/schemas/MediaStorageDTO'
        deploymentConfigurations:
          type: array
          items:
            type: string
        dataCaches:
          type: array
          items:
            type: string
        databaseSchemas:
          type: array
          items:
            $ref: '#/components/schemas/DatabaseSchemaDTO'
        clusters:
          type: array
          items:
            $ref: '#/components/schemas/ClusterDTO'
        live:
          type: boolean
        goLiveTime:
          type: string
          nullable: true
          format: date-time
        externalId:
          type: string
        disasterRecoveryType:
          type: string
          nullable: true
        dynatraceUrl:
          type: string
        activeDatabaseType:
          type: string
        sapProductNumber:
          type: string
          nullable: true
        crmTenantId:
          type: string
          nullable: true
        cloudPortalDeepLink:
          type: string
        subscriptionCode:
          type: string
        locked:
          type: boolean
        internalCustomer:
          type: boolean
        loggingUrl:
          type: string
        environmentPermissions:
          type: boolean
        wafConfig:
          nullable: true
        maxNumberOfSnapshots:
          type: integer
        scalingByCustomerAllowed:
          type: boolean
        environmentTemplateCode:
          type: string
        failover:
          type: boolean
        applicationCode:
          type: string
        blockPublicOutgoingTrafficState:
          type: string
        hibernationStatus:
          type: string
        httpPortEnabled:
          type: boolean
    WebProxyDTO:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        ipAddress:
          type: string
        defaultDnsEntry:
          type: string
        access:
          type: string
        ipFilteringSets:
          type: array
          items:
            type: string
        staticFileSet:
          type: string
          nullable: true
        status:
          type: string
    EndpointDTO:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        priority:
          type: integer
        domainName:
          type: string
        externalMonitoringPathUri:
          type: string
          nullable: true
        protocol:
          type: string
        k8sService:
          type: string
        k8sServiceVersion:
          type: string
        proxyTimeOut:
          type: integer
          nullable: true
        access:
          type: string
        sslCertificate:
          type: string
        mtlsCertificateCode:
          type: string
          nullable: true
        mtlsAllowedDomains:
          type: array
          items:
            type: string
        ipFilteringSets:
          type: array
          items:
            type: string
        redirectSets:
          type: array
          items:
            type: string
        staticFileSet:
          type: string
          nullable: true
        denyPathsSet:
          type: string
          nullable: true
        webProxy:
          type: string
        responseHeaderSet:
          type: string
          nullable: true
        customerAccessLevel:
          type: string
        maintenanceMode:
          type: boolean
        externalMonitoringStatus:
          type: string
        caching:
          $ref: '#/components/schemas/CachingDTO'
        wafConfig:
          nullable: true
        externallyMonitorable:
          type: boolean
    CachingDTO:
      type: object
      properties:
        code:
          type: string
        defaultExpire:
          type: integer
        maxExpire:
          type: integer
        paths:
          type: string
        enabled:
          type: boolean
    MediaStorageDTO:
      type: object
      required:
        - code
        - name
        - accountName
        - publicUrl
      properties:
        code:
          type: string
        name:
          type: string
        accountName:
          type: string
        publicUrl:
          type: string
        replication:
          type: string
        accessRestriction:
          type: string
        kind:
          type: string
    DatabaseSchemaDTO:
      type: object
      properties:
        code:
          type: string
        collation:
          type: string
        hyperscale:
          type: boolean
        oldestRestoreDate:
          type: string
          format: date-time
    ClusterDTO:
      type: object
      properties:
        code:
          type: string
