{
    parserClass="com.intellij.idea.plugin.hybris.polyglotQuery.PolyglotQueryParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

      psiClassPrefix="PolyglotQuery"
      psiImplClassSuffix="Impl"
      psiPackage="com.intellij.idea.plugin.hybris.polyglotQuery.psi"
      psiImplPackage="com.intellij.idea.plugin.hybris.polyglotQuery.psi.impl"

      elementTypeHolderClass="com.intellij.idea.plugin.hybris.polyglotQuery.psi.PolyglotQueryTypes"
      elementTypeClass="com.intellij.idea.plugin.hybris.polyglotQuery.PolyglotQueryElementType"
      tokenTypeClass="com.intellij.idea.plugin.hybris.polyglotQuery.PolyglotQueryTokenType"

      classHeader="generatedFilesHeader.txt"

      generate=[java='17']

      tokens = [
            IDENTIFIER      = 'regexp:([:letter:])([:letter:]|[:digit:]|_|\.)*'

            QUESTION_MARK       = '?'
            LBRACKET            = '['
            RBRACKET            = ']'
            LBRACE              = "{"
            RBRACE              = "}"
            AMP                 = '&'
            EQ                  = '='
            GT                  = '>'
            GTE                 = '>='
            LT                  = '<'
            LTE                 = '<='
            UNEQ                = '<>'
      ]

}
simpleFile ::= item_*
private item_ ::= (property|COMMENT|CRLF)
property ::= (KEY? SEPARATOR VALUE?) | KEY
